import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qa.abatoolbox.com/');
  await page.goto('https://qa.abatoolbox.com/login');
  await page.getByLabel('Company (Registered Acronym)').click();
  await page.getByLabel('Company (Registered Acronym)').fill('lc');
  await page.getByLabel('Username (Registered Email').click();
  await page.getByLabel('Username (Registered Email').fill('dorothyadmin@test.com');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Password1!');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('cell', { name: 'Aloha Le.' }).click();
  await page.getByRole('tab', { name: 'BX Treatments' }).click();
  await page.getByRole('button', { name: 'BX Treatment' }).click();
  await page.locator('div').filter({ hasText: /^Provider$/ }).first().click();
  await page.getByRole('option', { name: 'LaurieAdmin Test' }).click();
  await page.getByText('Target Behavior', { exact: true }).click();
  await page.getByLabel('Target Behavior (Max 90').click();
  await page.getByLabel('Target Behavior (Max 90').click();
  await page.getByLabel('Target Behavior (Max 90').fill('Percentage of Session Time');
  await page.locator('div').filter({ hasText: /^Bx Category \*$/ }).first().click();
  await page.getByRole('option', { name: 'Maladaptive Verbal Behavior' }).click();
  await page.locator('#q-portal--dialog--7').getByRole('button').first().click();
  await page.locator('#q-portal--dialog--5').getByRole('button').first().click();
  await page.getByRole('row', { name: '9/6/2024 1635 Rate Per Minute' }).locator('i').first().click();
  await page.getByRole('tab', { name: 'Target Interventions' }).locator('div').nth(1).click();
  await page.getByText('Add New Phase').click();
  await page.getByLabel('Phase Name *').click();
  await page.getByLabel('Phase Name *').click();
  await page.getByLabel('Phase Name *').fill('Percentage of Session Time');
  await page.locator('div').filter({ hasText: /^Modality Measurement\*$/ }).first().click();
  await page.getByRole('option', { name: 'Percentage of Session Time' }).click();
  await page.getByPlaceholder('Target Behavior *').click();
  await page.locator('#q-portal--dialog--11').getByText('Rate Per Minute').click();
});